# Generated by Django 4.1.3 on 2022-11-28 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traits", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trait",
            name="created_at",
        ),
    ]
