# Generated by Django 4.1.3 on 2022-11-29 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0001_initial"),
        ("traits", "0002_remove_trait_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="trait",
            name="pets",
            field=models.ManyToManyField(related_name="pets_traits", to="pets.pet"),
        ),
    ]
