# Generated by Django 4.1.3 on 2022-12-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traits", "0005_alter_trait_pets"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trait",
            name="pets",
        ),
    ]
