# Generated by Django 4.1.3 on 2022-11-28 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scientific_name", models.CharField(max_length=50, unique=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(2022, 11, 28, 20, 23, 53, 62722)
                    ),
                ),
            ],
        ),
    ]
