# Generated by Django 4.1.3 on 2022-12-01 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0001_initial"),
        ("groups", "0003_alter_group_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="pet",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pet_group",
                to="pets.pet",
            ),
        ),
    ]
