# Generated by Django 4.1.3 on 2022-12-01 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0005_alter_group_pet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="pet",
        ),
    ]
